name: learning09_TitlesActionbarAndHeaderFooter
description: $description
version: '${version}'

main: com.wady.learning09_TitlesActionbarAndHeaderFooter.Main
api-version: '26.1'

authors: [ Wady Jacoby ]
