name: learning02_spigot_commands
description: $description
version: '1.0-SNAPSHOT'

main: com.wady.learning02_spigot_commands.Main
api-version: '26.1'

authors: [ Wady Jacoby ]

commands:
  heal:
    description: insert description here
  teleportTenTwentyZero:
    description: my own tele command.

