name: learning04_commands_contd
description: $description
version: '1.0-SNAPSHOT'

main: com.wady.learning04_commands_contd.Main
api-version: '26.1'

authors: [ Wady Jacoby ]

commands:
  testCommand:
    description: just a test to see if args work!
  testConsoleCommand:
    description: just makes sure that there's a way to talk to the console
  config:

